Models/Hang.cs
using System;
using System.Collections.Generic;

namespace MyPhamCheilinus.Models;

public partial class Hang
{
    public string MaHang { get; set; } = null!;

    public string? TenHang { get; set; }

    public string? XuatXu { get; set; }

    public virtual ICollection<DanhMucSanPham> DanhMucSanPhams { get; set; } = new List<DanhMucSanPham>();
}

Areas/Admin/Controllers/HangsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using MyPhamCheilinus.Helpper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyPhamCheilinus.Models;
using PagedList.Core;
using System.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Runtime.InteropServices;

namespace MyPhamCheilinus.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Employee")]
    public class HangsController : Controller
    {
        private readonly _2023MyPhamContext _context;
        public INotyfService _notifyService { get; }

        public HangsController(_2023MyPhamContext context, INotyfService notifyService)
        {
            _context = context;
            _notifyService = notifyService;
        }

        // GET: Admin/Hangs
        public IActionResult Index(int? page, string? TenHang = "")
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 10;

            IQueryable<Hang> query = _context.Hangs
                .AsNoTracking();

            if (!string.IsNullOrEmpty(TenHang))
            {
                query = query.Where(x => x.TenHang.Contains(TenHang));
            }

            var lsProducts = query.OrderByDescending(x => x.MaHang).ToList();
            PagedList<Hang> models = new PagedList<Hang>(lsProducts.AsQueryable(), pageNumber, pageSize);


           ViewBag.CurrentPage = pageNumber;
           ViewBag.CurrentSearch = TenHang;


            return View(models);
        }
        // GET: Admin/Hangs/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Hangs == null)
            {
                return NotFound();
            }

            var hang = await _context.Hangs
                .FirstOrDefaultAsync(m => m.MaHang == id);
            if (hang == null)
            {
                return NotFound();
            }

            return View(hang);
        }

        public IActionResult Filtter( string? search)
        {
            var url = "/Admin/Hangs?";

            if (!string.IsNullOrEmpty(search))
            {
                url += $"TenHang={search}&";
            }

            // Loại bỏ dấu '&' cuối cùng nếu có
            if (url.EndsWith("&"))
            {
                url = url.Substring(0, url.Length - 1);
            }

            return Json(new { status = "success", redirectUrl = url });
        }

        // GET: Admin/Hangs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Hangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaHang,TenHang,XuatXu")] Hang hang)
        {
            if (ModelState.IsValid)
            {
                _context.Add(hang);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(hang);
        }

        // GET: Admin/Hangs/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Hangs == null)
            {
                return NotFound();
            }

            var hang = await _context.Hangs.FindAsync(id);
            if (hang == null)
            {
                return NotFound();
            }
            return View(hang);
        }

        // POST: Admin/Hangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("MaHang,TenHang,XuatXu")] Hang hang)
        {
            if (id != hang.MaHang)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hang);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HangExists(hang.MaHang))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(hang);
        }

        // GET: Admin/Hangs/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Hangs == null)
            {
                return NotFound();
            }

            var hang = await _context.Hangs
                .FirstOrDefaultAsync(m => m.MaHang == id);
            if (hang == null)
            {
                return NotFound();
            }

            return View(hang);
        }

        // POST: Admin/Hangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Hangs == null)
            {
                return Problem("Entity set '_2023MyPhamContext.Hangs' is null.");
            }

            var hang = await _context.Hangs.FindAsync(id);

            if (hang == null)
            {
                return NotFound();
            }

            // Xác nhận không có danh mục sản phẩm nào liên quan
            var danhMuc = await _context.DanhMucSanPhams.Where(p => p.MaHang == id).ToListAsync();

            // Xác nhận không có sản phẩm nào liên quan
            var products = _context.SanPhams
.AsEnumerable()
.Where(ct => danhMuc.Any(p => p.MaDanhMuc == ct.MaDanhMuc))
.ToList();
            // Xác nhận không có chi tiết đơn hàng nào liên quan
            var orderDetails = _context.ChiTietDonHangs
    .AsEnumerable()
    .Where(ct => products.Any(p => p.MaSanPham == ct.MaSanPham))
    .ToList();

            // Xóa chi tiết đơn hàng
            _context.RemoveRange(orderDetails);

            // Xóa sản phẩm
            _context.SanPhams.RemoveRange(products);
            _context.DanhMucSanPhams.RemoveRange(danhMuc);

            // Xóa Hãng sản phẩm
            _context.Hangs.Remove(hang);

            await _context.SaveChangesAsync();
            _notifyService.Success("Xóa hãng sản phẩm thành công");
            return RedirectToAction(nameof(System.Index));
        }


        private bool HangExists(string id)
    {
          return (_context.Hangs?.Any(e => e.MaHang == id)).GetValueOrDefault();
        }
    }
}

Areas/Admin/Views/Hangs/Create.cshtml
@model MyPhamCheilinus.Models.Hang

@{

    ViewData["Title"] = "Thêm mới hãng sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section Styles{
    <link href="~/Adminassets/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/Adminassets/summernote/summernote.css" rel="stylesheet" />
}
<form asp-controller="Hangs" asp-action="Create" asp-route-page="@ViewBag.CurrentPage" method="post" enctype="multipart/form-data">

    <section>
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-md-6">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="~/Home">Trang chủ</a></li>
                        <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Hangs" asp-action="Index" asp-route-page="@ViewBag.CurrentPage">Danh sách hãng sản phẩm</a></li>
                        <li class="breadcrumb-item active">Tạo mới hãng sản phẩm</li>
                    </ol>
                </div>
                <div class="col-md-6 text-right">
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <div class="page-header no-gutters has-tab">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Thông tin</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Mã hãng sản phẩm</label>
                        <input type="text" class="form-control" asp-for="MaHang" id="maSanPhamInput" />
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tên hãng sản phẩm</label>
                        <input type="text" class="form-control" asp-for="TenHang" />
                    </div>
                    <td class="row">
                        <button class="btn btn-primary">
                            <i class="anticon anticon-save"></i>
                            <span>Lưu thay đổi</span>
                        </button>
                        <button class="btn btn-secondary">
                            <a asp-area="Admin" asp-controller="Hangs" asp-action="Index" asp-route-MaID="@ViewBag.CurrentMaID" asp-route-page="@ViewBag.CurrentPage" asp-route-MaDM="@ViewBag.CurrentMaDM" asp-route-Search="@ViewBag.CurrentSearch" asp-route-MinPrice="@ViewBag.CurrentMinPrice" style="color: white" asp-route-MaxPrice="@ViewBag.CurrentMaxPrice">Trở lại</a>
                        </button>
                    </td>
                   
                </div>
            </div>
        </div>
     
    </div>
</form>


@section Scripts {
    <script>
        // Đảm bảo rằng trang đã tải hoàn toàn trước khi thực thi mã JavaScript
        $(document).ready(function () {
            // Gán giá trị mặc định cho cột Mã sản phẩm
            $("#maSanPhamInput").val("H");

            // Sử dụng sự kiện 'input' để theo dõi thay đổi trong cột Mã sản phẩm
            $("#maSanPhamInput").on('input', function () {
                var inputValue = $(this).val();
                // Kiểm tra nếu độ dài của giá trị nhập vào là 0 (trống) hoặc lớn hơn 6 ký tự, thì không thay đổi giá trị
                if (inputValue.length === 0) {
                    $(this).val("H");
                } else if (inputValue.length > 6) {
                    // Giới hạn độ dài tối đa là 6 ký tự
                    $(this).val(inputValue.slice(0, 6));
                }
            });
            CKEDITOR.replace('txtDetail', {
                customConfig: '/Content/ckeditor/config.js',
                extraAllowedContent: 'span',
            });
        });

    </script>
}

Areas/Admin/Views/Hangs/Delete.cshtml
@model MyPhamCheilinus.Models.Hang

@{

    ViewData["Title"] = "Xóa hãng sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="~/Home">Trang chủ</a></li>
                <a class="breadcrumb-item" asp-area="Admin" asp-controller="Loais" asp-action="Index">Danh sách hãng sản phẩm</a>
                <li class="breadcrumb-item active">Xóa hãng sản phẩm</li>
            </ol>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="card-body">
    <h3>Bạn có chắc muốn xóa hãng sản phẩm này?</h3>
    <div class="card">
        <div class="table">
            <table class="">
                <tbody>
                    <tr>
                        <td>Mã sản phẩm:</td>
                        <td class="text-dark font-weight-semibold">@Model.MaHang</td>
                    </tr>
                    <tr>
                        <td>Tên sản phẩm:</td>
                        <td class="text-dark font-weight-semibold">@Model.TenHang</td>
                    </tr>

                <td class="row">
                    <form asp-action="Delete" asp-for="MaHang" asp-route-page="@ViewBag.CurrentPage" asp-route-MaID="@ViewBag.CurrentMaID" asp-route-MaDM="@ViewBag.CurrentMaDM" asp-route-Search="@ViewBag.CurrentSearch" asp-route-MinPrice="@ViewBag.CurrentMinPrice" asp-route-MaxPrice="@ViewBag.CurrentMaxPrice">

                        <input type="submit" value="Xóa" class="btn btn-danger" /> |
                    </form>
                    <div>
                        <form asp-action="Index" asp-for="MaHang" asp-route-page="@ViewBag.CurrentPage" asp-route-MaID="@ViewBag.CurrentMaID" asp-route-MaDM="@ViewBag.CurrentMaDM" asp-route-Search="@ViewBag.CurrentSearch" asp-route-MinPrice="@ViewBag.CurrentMinPrice" asp-route-MaxPrice="@ViewBag.CurrentMaxPrice">
                            <input type="submit" class="btn btn-secondary" value="Trở lại" />
                        </form>
                    </div>

                </td>
                </tbody>
            </table>

        </div>
    </div>
</div>
@section Scripts {
    <script>
        // Đảm bảo rằng trang đã tải hoàn toàn trước khi thực thi mã JavaScript
        $(document).ready(function () {
            CKEDITOR.replace('txtDetail', {
                customConfig: '/Content/ckeditor/config.js',
                extraAllowedContent: 'span',
            });
        });

    </script>
}

Areas/Admin/Views/Hangs/Details.cshtml
@model MyPhamCheilinus.Models.Hang

@{
    ViewData["Title"] = "Chi tiết hãng sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="~/Home">Trang chủ</a></li>
                <a class="breadcrumb-item" asp-area="Admin" asp-controller="Hangs" asp-action="Index">Danh sách hãng sản phẩm</a>
                <li class="breadcrumb-item active">Chi tiết hãng sản phẩm</li>
            </ol>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="card-body">
    <h3>Thông tin chi tiết của hãng sản phẩm:</h3>
    <div class="card">
        <div class="table">
            <table class="">
                <tbody>
                    <tr>
                        <td>Mã hãng sản phẩm:</td>
                        <td class="text-dark font-weight-semibold">@Model.MaHang</td>
                    </tr>
                    <tr>
                        <td>Tên hãng sản phẩm:</td>
                        <td class="text-dark font-weight-semibold">@Model.TenHang</td>
                    </tr>
                    <tr>
                        <td>
                            <form asp-action="Index" asp-for="MaHang" asp-route-TenLoai="@ViewBag.CurrentLoai" asp-route-page="@ViewBag.CurrentPage">
                                <a asp-action="Edit" class="btn btn-success" asp-route-TenLoai="@ViewBag.CurrentLoai" asp-route-id="@Model.MaHang" asp-route-page="@ViewBag.CurrentPage">Sửa thông tin</a> |
                                <input type="submit" class="btn btn-secondary" id="backToList" value="Trở lại" />
                            </form>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

Areas/Admin/Views/Hangs/Edit.cshtml
@model MyPhamCheilinus.Models.Hang

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<form asp-controller="Hangs" asp-action="Edit" asp-route-id="@Model.MaHang" asp-route-MaID="@ViewBag.CurrentMaID" asp-route-page="@ViewBag.CurrentPage" asp-route-MaDM="@ViewBag.CurrentMaDM" asp-route-Search="@ViewBag.CurrentSearch" asp-route-MinPrice="@ViewBag.CurrentMinPrice" asp-route-MaxPrice="@ViewBag.CurrentMaxPrice" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="All" class="text-danger"></div>
    <input type="hidden" asp-for="MaHang" />
    <section>
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-md-6">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="~/Home">Trang chủ</a></li>
                        <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Hangs" asp-action="Index">Danh sách hãng sản phẩm</a></li>
                        <li class="breadcrumb-item active">Sửa thông tin hãng sản phẩm</li>
                    </ol>
                </div>
                <div class="col-md-6 text-right">
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <div class="page-header no-gutters has-tab">

        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Thông tin</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Mã hãng sản phẩm</label>
                        <input type="text" class="form-control" asp-for="MaHang" readonly />
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tên hãng sản phẩm</label>
                        <input type="text" class="form-control" asp-for="TenHang" />
                    </div>
                    <td class="row">
                        <button class="btn btn-primary">
                            <i class="anticon anticon-save"></i>
                            <span>Lưu thay đổi</span>
                        </button>
                        <button class="btn btn-secondary">
                            <a asp-area="Admin" asp-controller="Hangs" asp-action="Index" asp-route-MaID="@ViewBag.CurrentMaID" asp-route-page="@ViewBag.CurrentPage" asp-route-MaDM="@ViewBag.CurrentMaDM" asp-route-Search="@ViewBag.CurrentSearch" asp-route-MinPrice="@ViewBag.CurrentMinPrice" style="color: white" asp-route-MaxPrice="@ViewBag.CurrentMaxPrice">Trở lại</a>
                        </button>
                    </td>
                    </div>
                </div>
            </div>

        </div>
</form>
</div>
@section Scripts {
    <script>
        // Đảm bảo rằng trang đã tải hoàn toàn trước khi thực thi mã JavaScript
        $(document).ready(function () {
            CKEDITOR.replace('txtDetail', {
                customConfig: '/Content/ckeditor/config.js',
                extraAllowedContent: 'span',
            });
        });

    </script>
}

Areas/Admin/Views/Hangs/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<MyPhamCheilinus.Models.Hang>

@{
    int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<style>
    table thead th {
        background-color: #e6e6e6; /* Màu nền của đầu mục */
        color: #000; /* Màu chữ của đầu mục */
    }
</style>
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>DANH SÁCH HÃNG SẢN PHẨM</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="~/Home">Trang chủ</a></li>
                    <a class="breadcrumb-item" asp-area="Admin" asp-controller="Hangs" asp-action="Index">Danh sách hãng sản phẩm</a>
                    <li class="breadcrumb-item active"> Trang: @CurrentPage</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="row card-body">
                        <div class="col-lg-12">
                            <div class="d-md-flex">
                               
                                <div class="col-lg-3">
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Tìm kiếm theo tên hãng" id="searchName" value="@ViewBag.CurrentSearch" />
                                    </div>
                                </div>
                                <div class="col-lg-1">
                                    <div class="input-group-append">
                                        <button class="btn btn-outline-secondary" type="button" id="searchButton">Tìm kiếm</button>
                                    </div>
                                </div>
                                <div class="col-lg-8 text-right">
                                    <a class="btn btn-primary" asp-controller="Hangs" asp-action="Create" asp-route-page="@ViewBag.CurrentPage" asp-route-Search="@ViewBag.CurrentSearch" asp-route-MaID="@ViewBag.CurrentMaID" ><i class="anticon anticon-plus-circle m-r-5"></i> <span>Thêm hãng sản phẩm</span></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr class="text-center">
                                    <th style="width : 5%">STT</th>
                                    <th>Hãng sản phẩm</th>
                                    <th>Chức năng</th>
                                </tr>
                            </thead>
                            <tbody id="records_table">
                                @if (Model != null)
                                {
                                    var i = 1;
                                    foreach (var item in Model)
                                    {
                                        <tr>
                                            <td class="text-center">@i</td>
                                            <td>
                                                <div class="d-flex align-items-center">
                                                    <h6 class="m-b-0 m-l-10">@item.TenHang</h6>
                                                </div>
                                            </td>
                                 
                                            <td class="text-right">
                                                <a class="btn btn-info btn-tone m-r-5" asp-action="Details" asp-route-id="@item.MaHang" asp-route-MaID="@ViewBag.CurrentMaID" asp-route-page="@ViewBag.CurrentPage" asp-route-Search="@ViewBag.CurrentSearch">Chi tiết</a>
                                                <a class="btn btn-success btn-tone m-r-5" asp-action="Edit" asp-route-id="@item.MaHang" asp-route-MaID="@ViewBag.CurrentMaID" asp-route-page="@ViewBag.CurrentPage" asp-route-Search="@ViewBag.CurrentSearch">Sửa</a>
                                                <a class="btn btn-danger btn-tone m-r-5" asp-action="Delete" asp-route-id="@item.MaHang" asp-route-MaID="@ViewBag.CurrentMaID" asp-route-page="@ViewBag.CurrentPage" asp-route-Search="@ViewBag.CurrentSearch">Xóa</a>
                                            </td>
                                        </tr>
                                        i++;
                                    }
                                }
                            </tbody>
                        </table>

                            <div class="card-body">
        
                                    <div aria-label="Page navigation example" class="d-flex justify-content-center">
                            <ul class="pagination">
                                <li class="page-item @(Model.HasPreviousPage ? "" : "disabled")">
                                    <a class="page-link" asp-action="Index" asp-route-page="1" asp-route-MaID="@ViewBag.Current" aMaIDsp-route-Search="@ViewBag.CurrentSearch"><<</a>
                                </li>
                                <li class="page-item @(Model.HasPreviousPage ? "" : "disabled")">
                                    <a class="page-link" asp-action="Index" asp-route-page="@(Model.PageNumber - 1)" asp-route-MaID="@ViewBag.Current" aMaIDsp-route-Search="@ViewBag.CurrentSearch"><</a>
                                </li>
                                @if (Model.PageCount <= 3)
                                {
                                    for (int page = 1; page <= Model.PageCount; page++)
                                    {
                                        <li class="page-item @(page == Model.PageNumber ? "active" : "")">
                                            <a class="page-link" asp-action="Index" asp-route-page="@(page)" asp-route-MaID="@ViewBag.Current" aMaIDsp-route-Search="@ViewBag.CurrentSearch">@(page)</a>
                                        </li>
                                    }
                                }
                                else
                                {
                                    var startPage = Math.Max(1, Model.PageNumber - 1);
                                    var endPage = Math.Min(Model.PageCount, startPage + 2);

                                    if (startPage == 2)
                                    {
                                        <li class="page-item">
                                            <a class="page-link" asp-action="Index" asp-route-page="1" asp-route-MaID="@ViewBag.Current" aMaIDsp-route-Search="@ViewBag.CurrentSearch">1</a>
                                        </li>
                                    }
                                    else if (startPage > 2)
                                    {
                                        <li class="page-item">
                                            <a class="page-link" asp-action="Index" asp-route-page="1" asp-route-MaID="@ViewBag.Current" aMaIDsp-route-Search="@ViewBag.CurrentSearch" asp-route-MaxPrice="@ViewBag.CurrentMaxPrice">1</a>
                                        </li>
                                        <li class="page-item disabled">
                                            <span class="page-link">...</span>
                                        </li>
                                    }

                                    for (int page = startPage; page <= endPage; page++)
                                    {
                                        <li class="page-item @(page == Model.PageNumber ? "active" : "")">
                                            <a class="page-link" asp-action="Index" asp-route-page="@(page)" asp-route-MaID="@ViewBag.Current" aMaIDsp-route-Search="@ViewBag.CurrentSearch">@(page)</a>
                                        </li>
                                    }

                                    if (endPage == Model.PageCount - 1)
                                    {

                                        <li class="page-item">
                                            <a class="page-link" asp-action="Index" asp-route-page="@Model.PageCount" asp-route-MaID="@ViewBag.Current" aMaIDsp-route-Search="@ViewBag.CurrentSearch">@Model.PageCount</a>
                                        </li>
                                    }
                                    else if (endPage < Model.PageCount - 1)
                                    {
                                        <li class="page-item disabled">
                                            <span class="page-link">...</span>
                                        </li>
                                        <li class="page-item">
                                            <a class="page-link" asp-action="Index" asp-route-page="@Model.PageCount" asp-route-MaID="@ViewBag.Current" aMaIDsp-route-Search="@ViewBag.CurrentSearch">@Model.PageCount</a>
                                        </li>
                                    }
                                }

                                <li class="page-item @(Model.HasNextPage ? "" : "disabled")">
                                    <a class="page-link" asp-action="Index" asp-route-page="@(Model.PageNumber + 1)" asp-route-MaID="@ViewBag.Current" aMaIDsp-route-Search="@ViewBag.CurrentSearch">></a>
                                </li>
                                <li class="page-item @(Model.HasNextPage ? "" : "disabled")">
                                    <a class="page-link" asp-action="Index" asp-route-page="@Model.PageCount" asp-route-MaID="@ViewBag.Current" aMaIDsp-route-Search="@ViewBag.CurrentSearch">>></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    </div>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
</section>

<style>
    .image-modal {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.7);
        display: flex;
        align-items: center;
        justify-content: center;
        z-index: 999;
    }

        .image-modal img {
            max-width: 90%;
            max-height: 90%;
        }
</style>

@section Scripts{
    <script>
        $(document).ready(function () {
            // Xử lý sự kiện khi nút Tìm kiếm được nhấn
            $('#searchButton').click(function () {
                var search = $('#searchName').val();
                $.ajax({
                    url: '/Admin/Hangs/Filtter',
                    datatype: 'json',
                    type: 'GET',
                    data: {
                        search: search,
                    },
                    async: true,
                    success: function (results) {
                        if (results.status == 'success') {
                            window.location.href = results.redirectUrl;
                        }
                    },
                    error: function (xhr) {
                        alert('error');
                    }
                });
            });

        });
    </script>
}