Models/SanPham.cs
using System;
using System.Collections.Generic;

namespace MyPhamCheilinus.Models;

public partial class SanPham
{
    public string MaSanPham { get; set; } = null!;

    public string? TenSanPham { get; set; }

    public string? Mau { get; set; }

    public string? Anh { get; set; }

    public double? Gia { get; set; }

    public double? KhuyenMai { get; set; }

    public int? Slkho { get; set; }

    public DateTime? NgaySx { get; set; }

    public int? LuotMua { get; set; }

    public string? MaDanhMuc { get; set; }

    public bool HomeFlag { get; set; }

    public bool BestSellers { get; set; }

    public string? MoTa { get; set; }

    public bool Active { get; set; }

    public DateTime? NgaySua { get; set; }

    public double? GiaNhap { get; set; }

    public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; } = new List<ChiTietDonHang>();

    public virtual ICollection<ChiTietLoHang> ChiTietLoHangs { get; set; } = new List<ChiTietLoHang>();

    public virtual DanhMucSanPham? MaDanhMucNavigation { get; set; }
}

Areas/Admin/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using MyPhamCheilinus.Helpper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyPhamCheilinus.Models;
using PagedList.Core;
using System.Data;
using Microsoft.AspNetCore.Authorization;

namespace MyPhamCheilinus.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Employee")]
    public class SanPhamsController : Controller
    {
        private readonly _2023MyPhamContext _context;
        public INotyfService _notifyService { get; }

        public SanPhamsController(_2023MyPhamContext context, INotyfService notifyService)
        {
            _context = context;
            _notifyService = notifyService;
        }

        // GET: Admin/SanPhams
        public IActionResult Index(int? page, string MaDM = "", string? MaID = "", string search = "", double? minPrice = null, double? maxPrice = null)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 10;

            IQueryable<SanPham> query = _context.SanPhams
                .AsNoTracking()
                .Include(x => x.MaDanhMucNavigation);

            if (!string.IsNullOrEmpty(MaDM))
            {
                query = query.Where(x => x.MaDanhMuc == MaDM);
            }
            if (!string.IsNullOrEmpty(MaID))
            {
                query = query.Where(x => x.MaSanPham.Contains(MaID));
            }


            if (!string.IsNullOrEmpty(search))
            {
                query = query.Where(x => x.TenSanPham.Contains(search));
            }

            if (minPrice != null)
            {
                query = query.Where(x => x.Gia >= minPrice);
            }

            if (maxPrice != null)
            {
                query = query.Where(x => x.Gia <= maxPrice);
            }

            var lsProducts = query.OrderByDescending(x => x.MaSanPham).ToList();

            PagedList<SanPham> models = new PagedList<SanPham>(lsProducts.AsQueryable(), pageNumber, pageSize);
            ViewBag.CurrentMaDM = MaDM;
            ViewBag.CurrentPage = pageNumber;
            ViewBag.CurrentSearch = search;
            ViewBag.CurrentMaID = MaID;
            ViewBag.CurrentMinPrice = minPrice;
            ViewBag.CurrentMaxPrice = maxPrice;  // Thiếu dấu "." ở đây.
            ViewData["DanhMuc"] = new SelectList(_context.DanhMucSanPhams, "MaDanhMuc", "TenDanhMuc", MaDM);

            return View(models);
        }



        public IActionResult Filtter(string MaDM, string search, double? minPrice, double? maxPrice, string? MaID)
        {
            var url = "/Admin/SanPhams?";
            if (MaID != null)
            {
                url += $"MaID={MaID}&";
            }
            if (!string.IsNullOrEmpty(MaDM))
            {
                url += $"MaDM={MaDM}&";
            }

            if (!string.IsNullOrEmpty(search))
            {
                url += $"search={search}&";
            }

            if (minPrice != null)
            {
                url += $"minPrice={minPrice}&";
            }

            if (maxPrice != null)
            {
                url += $"maxPrice={maxPrice}&";
            }

            // Loại bỏ dấu '&' cuối cùng nếu có
            if (url.EndsWith("&"))
            {
                url = url.Substring(0, url.Length - 1);
            }

            return Json(new { status = "success", redirectUrl = url });
        }





        // GET: Admin/SanPhams/Details/5
        public async Task<IActionResult> Details(string id, int? page, string? MaID, string? search, string? MaDM, double? minPrice, double? maxPrice)
        {
            if (id == null || _context.SanPhams == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPhams
                .Include(s => s.MaDanhMucNavigation)
                .FirstOrDefaultAsync(m => m.MaSanPham == id);
            if (sanPham == null)
            {
                return NotFound();
            }
          ViewBag.CurrentPage = page;
            ViewBag.CurrentSearch = search;
            ViewBag.CurrentMaDM = MaDM;
            ViewBag.CurrentMinPrice = minPrice;
            ViewBag.CurrentMaxPrice = maxPrice;
            ViewBag.CurrentMaID = MaID;
            return View(sanPham);
        }
        [HttpPost, ActionName("Details")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DetailsConfirmed(string id, int? page, string? MaID, string? search, string? MaDM, double? minPrice, double? maxPrice)
        {
            if (_context.SanPhams == null)
            {
                return Problem("Entity set '_2023MyPhamContext.SanPhams' is null.");
            }
            // Sau khi xóa thành công, bạn có thể chuyển hướng trở lại trang chứa sản phẩm vừa xóa bằng cách truyền tham số `page`.
            // Nếu `page` không có giá trị, bạn có thể mặc định nó về một trang cụ thể (ví dụ: 1).
            return RedirectToAction("Index", new { page = page, MaDM = MaDM, MaID = MaID, search = search, minPrice = minPrice, maxPrice = maxPrice });

        }

        // GET: Admin/SanPhams/Create
        public IActionResult Create(int? page, string? search, string? MaDM, string? MaID, double? minPrice, double? maxPrice)
        {
            ViewData["DanhMuc"] = new SelectList(_context.DanhMucSanPhams, "MaDanhMuc", "TenDanhMuc");
            ViewBag.CurrentPage = page;
            ViewBag.CurrentSearch = search;
            ViewBag.CurrentMaDM = MaDM;
            ViewBag.CurrentMinPrice = minPrice;
            ViewBag.CurrentMaxPrice = maxPrice;
            ViewBag.CurrentMaID = MaID;
            return View();
        }

        // POST: Admin/SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int? page, [Bind("MaSanPham,TenSanPham,Mau,Anh,Gia,KhuyenMai,Slkho,GiaNhap,NgaySx,LuotMua,MaDanhMuc,HomeFlag,BestSellers,MoTa,Active")] SanPham sanPham, IFormFile? fAnh)

        {
            if (string.IsNullOrEmpty(sanPham.MaSanPham))
            {
                ModelState.AddModelError("MaSanPham", "Mã sản phẩm là trường bắt buộc.");
            }

            if (string.IsNullOrEmpty(sanPham.TenSanPham))
            {
                ModelState.AddModelError("TenSanPham", "Xin hãy nhập tên của sản phẩm.");
            }

            if (sanPham.Gia < 0)
            {
                ModelState.AddModelError("Gia", "Giá bán phải lớn hơn hoặc bằng 0");
            }
            if (sanPham.Gia == null)
            {
                ModelState.AddModelError("Gia", "Xin hãy nhập giá bán của sản phẩm.");
            }

            if (sanPham.Slkho == null)
            {
                ModelState.AddModelError("Slkho", "Xin hãy nhập số lượng tồn kho.");
            }
            if (sanPham.Slkho < 0)
            {
                ModelState.AddModelError("Slkho", "Số lượng phải lớn hơn hoặc bằng 0");
            }
            if (sanPham.GiaNhap == null)
            {
                ModelState.AddModelError("GiaNhap", "Xin hãy điền giá nhập của sản phẩm.");
            }
            if (sanPham.GiaNhap < 0)
            {
                ModelState.AddModelError("GiaNhap", "Giá nhập hàng phải lớn hơn hoặc bằng 0");
            }
            if (sanPham.MaDanhMuc == null)
            {
                ModelState.AddModelError("MaDanhMuc", "Xin hãy chọn danh mục sản phẩm.");
            }
            if (sanPham.MoTa == null)
            {
                ModelState.AddModelError("MoTa", "Xin hãy điền mô tả sản phẩm.");
            }
            if (sanPham.Mau == null)
            {
                ModelState.AddModelError("Mau", "Xin hãy điền màu  sản phẩm.");
            }
            if (ModelState.IsValid)
            {
                if (_context.SanPhams.Any(x => x.MaSanPham == sanPham.MaSanPham))
                {
                    ModelState.AddModelError("MaSanPham", "Mã sản phẩm đã tồn tại. Vui lòng chọn mã khác.");
                    ViewData["DanhMuc"] = new SelectList(_context.DanhMucSanPhams, "MaDanhMuc", "TenDanhMuc", sanPham.MaDanhMuc);
                    return View(sanPham);
                }

                sanPham.TenSanPham = Utilities.ToTitleCase(sanPham.TenSanPham);
                if (fAnh != null)
                {
                    string extention = Path.GetExtension(fAnh.FileName);
                    string image = Utilities.SEOUrl(sanPham.TenSanPham) + extention;
                    sanPham.Anh = await Utilities.UploadFile(fAnh, @"sanPhams", image.ToLower());
                }
                //if (string.IsNullOrEmpty(sanPham.Anh)) sanPham.Anh = "default.jpg";

                //sanPham.NgaySx = DateTime.Now;
                sanPham.NgaySx = DateTime.Now;
                _context.Add(sanPham);
                await _context.SaveChangesAsync();
                _notifyService.Success("Tạo mới sản phẩm thành công");
                return RedirectToAction("Index", new {page = page});
            }
            ViewData["DanhMuc"] = new SelectList(_context.DanhMucSanPhams, "MaDanhMuc", "TenDanhMuc", sanPham.MaDanhMuc);
            return View(sanPham);
        }

        // GET: Admin/SanPhams/Edit/5
        public async Task<IActionResult> Edit(string id, int? page, string? MaID, string? search, string? MaDM, double? minPrice, double? maxPrice)
        {
            if (id == null || _context.SanPhams == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPhams.FindAsync(id);
            if (sanPham == null)
            {

Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyPhamCheilinus.Models;

namespace MyPhamCheilinus.Controllers
{
    public class SanPhamsController : Controller
    {
        private readonly _2023MyPhamContext _context;

        public SanPhamsController(_2023MyPhamContext context)
        {
            _context = context;
        }

        // GET: SanPhams
        public async Task<IActionResult> Index()
        {
            var _2023MyPhamContext = _context.SanPhams.Include(s => s.MaDanhMucNavigation);
            return View(await _2023MyPhamContext.ToListAsync());
        }

        // GET: SanPhams/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.SanPhams == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPhams
                .Include(s => s.MaDanhMucNavigation)
                .FirstOrDefaultAsync(m => m.MaSanPham == id);
            if (sanPham == null)
            {
                return NotFound();
            }

            return View(sanPham);
        }

        // GET: SanPhams/Create
        public IActionResult Create()
        {
            ViewData["MaDanhMuc"] = new SelectList(_context.DanhMucSanPhams, "MaDanhMuc", "MaDanhMuc");
            return View();
        }

        // POST: SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaSanPham,TenSanPham,Mau,Anh,Gia,KhuyenMai,Slkho,NgaySx,LuotMua,MaDanhMuc")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sanPham);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaDanhMuc"] = new SelectList(_context.DanhMucSanPhams, "MaDanhMuc", "MaDanhMuc", sanPham.MaDanhMuc);
            return View(sanPham);
        }

        // GET: SanPhams/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.SanPhams == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPhams.FindAsync(id);
            if (sanPham == null)
            {
                return NotFound();
            }
            ViewData["MaDanhMuc"] = new SelectList(_context.DanhMucSanPhams, "MaDanhMuc", "MaDanhMuc", sanPham.MaDanhMuc);
            return View(sanPham);
        }

        // POST: SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("MaSanPham,TenSanPham,Mau,Anh,Gia,KhuyenMai,Slkho,NgaySx,LuotMua,MaDanhMuc")] SanPham sanPham)
        {
            if (id != sanPham.MaSanPham)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sanPham);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SanPhamExists(sanPham.MaSanPham))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaDanhMuc"] = new SelectList(_context.DanhMucSanPhams, "MaDanhMuc", "MaDanhMuc", sanPham.MaDanhMuc);
            return View(sanPham);
        }

        // GET: SanPhams/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.SanPhams == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPhams
                .Include(s => s.MaDanhMucNavigation)
                .FirstOrDefaultAsync(m => m.MaSanPham == id);
            if (sanPham == null)
            {
                return NotFound();
            }

            return View(sanPham);
        }

        // POST: SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.SanPhams == null)
            {
                return Problem("Entity set '_2023MyPhamContext.SanPhams'  is null.");
            }
            var sanPham = await _context.SanPhams.FindAsync(id);
            if (sanPham != null)
            {
                _context.SanPhams.Remove(sanPham);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SanPhamExists(string id)
        {
          return (_context.SanPhams?.Any(e => e.MaSanPham == id)).GetValueOrDefault();
        }
    }
}

Areas/Admin/Views/SanPhams/Create.cshtml
@model MyPhamCheilinus.Models.SanPham

@{

    ViewData["Title"] = "Thêm mới sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section Styles{
    <link href="~/Adminassets/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/Adminassets/summernote/summernote.css" rel="stylesheet" />
}
<form asp-controller="SanPhams" asp-action="Create" asp-route-page="@ViewBag.CurrentPage" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="All" class="text-danger"></div>
    <input type="hidden" asp-for="Anh" />
    <section>
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-md-6">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="~/Home">Trang chủ</a></li>
                        <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="SanPhams" asp-action="Index" asp-route-page="@ViewBag.CurrentPage">Danh sách sản phẩm</a></li>
                        <li class="breadcrumb-item active">Tạo mới sản phẩm</li>
                    </ol>
                </div>
                <div class="col-md-6 text-right">
                    
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <div class="page-header no-gutters has-tab">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Thông tin</a>
            </li>
@*            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">Thông tin tùy chọn</a>
            </li>*@
           @* <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">Mô tả</a>
            </li>*@
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Mã sản phẩm</label>
                        <input type="text" class="form-control" asp-for="MaSanPham" id="maSanPhamInput" />
                    </div>


                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tên sản phẩm</label>
                        <input type="text" class="form-control" asp-for="TenSanPham" />
                    </div>
                  @*  <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Mô tả ngắn</label>
                        <input type="text" class="form-control" asp-for="MoTa" />
                    </div>*@
                    <div class="form-group">
                        <label for="inputDescription"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Mô tả sản phẩm</font></font></label>
                        <textarea id="txtDetail" class="form-control" asp-for="MoTa" rows="4" style="height: 119px;"></textarea>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-4">
                            <label class="font-weight-semibold" for="productPrice">Giá bán</label>
                            <input type="number" class="form-control" asp-for="Gia" step="0.01">
                        </div>
                        <div class="form-group col-md-4">
                            <label class="font-weight-semibold" for="productPrice">Giá nhập</label>
                            <input type="number" class="form-control" asp-for="GiaNhap" step="0.01">
                        </div>
                        <div class="form-group col-md-4">
                            <label class="font-weight-semibold" for="productPrice">Giảm giá (%)</label>
                            <input type="number" class="form-control" asp-for="KhuyenMai" step="0.01">
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="productCategory">Danh mục sản phẩm</label>
                            <select class="custom-select" asp-for="MaDanhMuc" style="min-width: 200px" asp-items="ViewBag.DanhMuc">
                                <option value="" disabled selected>Chọn danh mục</option>
                            </select>
                        </div>
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="productName">Số lượng tồn kho</label>
                            <input type="number" class="form-control" asp-for="Slkho" step="1">
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="productAnh">Ảnh đại diện</label>
                            <input type="file" name="fAnh" class="form-control-file" asp-for="Anh">
                            <span asp-validation-for="Anh" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="productName">Mã màu</label>
                            <input type="color" id="Mau" name="Mau" class="form-control" asp-for="Mau" />
                        </div>
                    </div>
                    
                    
                  
                    <td class="row">
                        <button class="btn btn-primary">
                            <i class="anticon anticon-save"></i>
                            <span>Thêm sản phẩm</span>
                        </button>
                        <button class="btn btn-secondary">
                            <a asp-area="Admin" asp-controller="SanPhams" asp-action="Index" asp-route-page="@ViewBag.CurrentPage" asp-route-MaID="@ViewBag.CurrentMaID" asp-route-MaDM="@ViewBag.CurrentMaDM" asp-route-Search="@ViewBag.CurrentSearch" asp-route-MinPrice="@ViewBag.CurrentMinPrice" style="color: white" asp-route-MaxPrice="@ViewBag.CurrentMaxPrice">Trở lại</a>
                        </button>
                    </td>
                    @*<div class="row">
                        <div class="m-t-25">
                            <div class="form-group d-flex align-items-center">
                                <div class="switch m-r-10">
                                    <input type="checkbox" asp-for="Active" checked="">
                                    <label for="Active"></label>
                                </div>
                                <label>Trạng thái</label>
                            </div>
                            <div class="form-group d-flex align-items-center">
                                <div class="switch m-r-10">
                                    <input type="checkbox" asp-for="HomeFlag">
                                    <label for="HomeFlag"></label>
                                </div>
                                <label>HomeFlag</label>
                            </div>
                            <div class="form-group d-flex align-items-center">
                                <div class="switch m-r-10">
                                    <input type="checkbox" asp-for="BestSellers" disabled="">
                                    <label for="BestSellers"></label>
                                </div>
                                <label>Yêu thích</label>
                            </div>
                        </div>
                    </div>*@
                </div>
            </div>
        </div>
        @*<div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productSize">Size</label>
                        <input type="text" class="form-control" asp-for="Slkho" />
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">Colors</label>
                        <select class="select2" id="productColors" multiple="multiple">
                            @foreach (var color in ViewBag.Colors)
                            {
                                <option value="@color.Value">@color.Text</option>
                            }
                        </select>
                    </div>

                </div>
            </div>
        </div>*@
        @*<div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label for="inputDescription"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Mô tả sản phẩm</font></font></label>
                        <textarea id="inputDescription" class="form-control" rows="4" style="height: 119px;"></textarea>
                    </div>
                </div>
            </div>
        </div>*@
    </div>
</form>


@section Scripts {
    <script>
        // Đảm bảo rằng trang đã tải hoàn toàn trước khi thực thi mã JavaScript
        $(document).ready(function () {
            // Gán giá trị mặc định cho cột Mã sản phẩm
            $("#maSanPhamInput").val("SP00");

            // Sử dụng sự kiện 'input' để theo dõi thay đổi trong cột Mã sản phẩm
            $("#maSanPhamInput").on('input', function () {
                var inputValue = $(this).val();
                // Kiểm tra nếu độ dài của giá trị nhập vào là 0 (trống) hoặc lớn hơn 6 ký tự, thì không thay đổi giá trị
                if (inputValue.length === 0) {
                    $(this).val("SP00");
                } else if (inputValue.length > 6) {
                    // Giới hạn độ dài tối đa là 6 ký tự
                    $(this).val(inputValue.slice(0, 6));
                }
            });
            CKEDITOR.replace('txtDetail', {
                customConfig: '/Content/ckeditor/config.js',
                extraAllowedContent: 'span',
            });
        });

    </script>
}