Models/Loai.cs
using System;
using System.Collections.Generic;

namespace MyPhamCheilinus.Models;

public partial class Loai
{
    public string MaLoai { get; set; } = null!;

    public string? TenLoai { get; set; }

    public virtual ICollection<Ctloai> Ctloais { get; set; } = new List<Ctloai>();
}

Areas/Admin/Controllers/LoaisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using MyPhamCheilinus.Helpper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyPhamCheilinus.Models;
using PagedList.Core;
using System.Data;
using Microsoft.AspNetCore.Authorization;

namespace MyPhamCheilinus.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Employee")]
    public class LoaisController : Controller
    {
        private readonly _2023MyPhamContext _context;
        public INotyfService _notifyService { get; }

        public LoaisController(_2023MyPhamContext context, INotyfService notifyService)
        {
            _context = context;
            _notifyService = notifyService;
        }

        // GET: Admin/Loais
        public IActionResult Index(int? page, string? TenLoai = "")
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 10;

            IQueryable<Loai> query = _context.Loais
                .AsNoTracking();

            if (!string.IsNullOrEmpty(TenLoai))
            {
                query = query.Where(x => x.TenLoai.Contains(TenLoai));
            }

            var lsProducts = query.OrderByDescending(x => x.MaLoai).ToList();
            PagedList<Loai> models = new PagedList<Loai>(lsProducts.AsQueryable(), pageNumber, pageSize);
     
            ViewBag.CurrentPage = pageNumber;
            ViewBag.CurrentLoai = TenLoai;


            return View(models);
        }
        public IActionResult Filtter(string? TenLoai)
        {
            var url = "/Admin/Loais?";

            if (!string.IsNullOrEmpty(TenLoai))
            {
                url += $"TenLoai={TenLoai}&";
            }

            // Loại bỏ dấu '&' cuối cùng nếu có
            if (url.EndsWith("&"))
            {
                url = url.Substring(0, url.Length - 1);
            }

            return Json(new { status = "success", redirectUrl = url });
        }
        // GET: Admin/Loais/Details/5
        public async Task<IActionResult> Details(string id, int? page,string? TenLoai)
        {
            if (id == null || _context.Loais == null)
            {
                return NotFound();
            }

            var loai = await _context.Loais
                .FirstOrDefaultAsync(m => m.MaLoai == id);
            if (loai == null)
            {
                return NotFound();
            }
            ViewBag.CurrentPage = page;
            ViewBag.CurrentLoai = TenLoai;
            return View(loai);
        }
        [HttpPost, ActionName("Details")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DetailsConfirmed(string id, int? page, string? TenLoai)
        {
            if (_context.SanPhams == null)
            {
                return Problem("Entity set '_2023MyPhamContext.SanPhams' is null.");
            }
            // Sau khi xóa thành công, bạn có thể chuyển hướng trở lại trang chứa sản phẩm vừa xóa bằng cách truyền tham số `page`.
            // Nếu `page` không có giá trị, bạn có thể mặc định nó về một trang cụ thể (ví dụ: 1).
            return RedirectToAction("Index", new { page = page, TenLoai = TenLoai});

        }
        // GET: Admin/Loais/Create
        public IActionResult Create(int? page, string? TenLoai)
        {
          
            return View();
        }

        // POST: Admin/Loais/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int? page, string? TenLoai,[Bind("MaLoai,TenLoai")] Loai loai)
        {
            if (string.IsNullOrEmpty(loai.MaLoai))
            {
                ModelState.AddModelError("MaLoai", "Mã loại sản phẩm là trường bắt buộc.");
            }

            if (string.IsNullOrEmpty(loai.TenLoai))
            {
                ModelState.AddModelError("TenLoai", "Xin hãy nhập tên của loại sản phẩm.");
            }
            if (ModelState.IsValid)
            {
                _context.Add(loai);
                await _context.SaveChangesAsync();
                _notifyService.Success("Tạo mới sản phẩm thành công");
                return RedirectToAction("Index", new { page = page, TenLoai = TenLoai });
            }
            return View(loai);
        }

        // GET: Admin/Loais/Edit/5
        public async Task<IActionResult> Edit(string id, int? page, string? TenLoai)
        {
            if (id == null || _context.Loais == null)
            {
                return NotFound();
            }

            var loai = await _context.Loais.FindAsync(id);
            if (loai == null)
            {
                return NotFound();
            }
            ViewBag.CurrentPage = page;
            ViewBag.CurrentLoai = TenLoai;
            return View(loai);
        }

        // POST: Admin/Loais/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, int? page, string? TenLoai, [Bind("MaLoai,TenLoai")] Loai loai)
        {
            if (id != loai.MaLoai)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(loai);
                    await _context.SaveChangesAsync();
                    _notifyService.Success("Cập nhật sản phẩm thành công");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LoaiExists(loai.MaLoai))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", new { page = page, TenLoai = TenLoai });
            }
            return View(loai);
        }

        // GET: Admin/Loais/Delete/5
        public async Task<IActionResult> Delete(string id, int? page, string? TenLoai)
        {
            if (id == null || _context.Loais == null)
            {
                return NotFound();
            }

            var loai = await _context.Loais
                .FirstOrDefaultAsync(m => m.MaLoai == id);
            if (loai == null)
            {
                return NotFound();
            }
            ViewBag.CurrentPage = page;
            ViewBag.CurrentLoai = TenLoai;
            return View(loai);
        }

        // POST: Admin/Loais/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id, int? page, string? TenLoai)
        {
            if (_context.Loais == null)
            {
                return Problem("Entity set '_2023MyPhamContext.Loais'  is null.");
            }
            var loai = await _context.Loais.FindAsync(id);
            if (loai == null)
            {
                return NotFound();
            }
            // Xác nhận không có chi tiết loại nào liên quan
            var ctloai = await _context.Ctloais.Where(p => p.MaLoai == id).ToListAsync();

            // Xác nhận không có danh mục sản phẩm nào liên quan

            var danhMuc = _context.DanhMucSanPhams
     .AsEnumerable()
     .Where(ct => ctloai.Any(p => p.MaCtloai == ct.MaCtloai))
     .ToList();
            // Xác nhận không có sản phẩm nào liên quan
            var products = _context.SanPhams
                             .AsEnumerable()
                            .Where(ct => danhMuc.Any(p => p.MaDanhMuc == ct.MaDanhMuc))
                            .ToList();
            // Xác nhận không có chi tiết đơn hàng nào liên quan
            var orderDetails = _context.ChiTietDonHangs
    .AsEnumerable()
    .Where(ct => products.Any(p => p.MaSanPham == ct.MaSanPham))
    .ToList();

            // Xóa chi tiết đơn hàng
            _context.RemoveRange(orderDetails);

            // Xóa sản phẩm
            _context.SanPhams.RemoveRange(products);
            _context.DanhMucSanPhams.RemoveRange(danhMuc);
            _context.Ctloais.RemoveRange(ctloai);
            // Xóa Hãng sản phẩm
            _context.Loais.Remove(loai);

            await _context.SaveChangesAsync();
            _notifyService.Success("Xóa loại sản phẩm thành công");
        
            return RedirectToAction("Index", new { page = page, TenLoai = TenLoai });
        }

        private bool LoaiExists(string id)
        {
          return (_context.Loais?.Any(e => e.MaLoai == id)).GetValueOrDefault();
        }
    }
}

Areas/Admin/Views/Loais/Create.cshtml
@model MyPhamCheilinus.Models.Loai

@{

    ViewData["Title"] = "Thêm mới loại sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section Styles{
    <link href="~/Adminassets/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/Adminassets/summernote/summernote.css" rel="stylesheet" />
}
<form asp-controller="Loais" asp-action="Create" asp-route-page="@ViewBag.CurrentPage" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="All" class="text-danger"></div>
    <section>
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-md-6">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="~/Home">Trang chủ</a></li>
                        <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Loais" asp-action="Index" asp-route-page="@ViewBag.CurrentPage">Danh sách loại sản phẩm</a></li>
                        <li class="breadcrumb-item active">Tạo mới loại sản phẩm</li>
                    </ol>
                </div>
                <div class="col-md-6 text-right">
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <div class="page-header no-gutters has-tab">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Thông tin</a>
            </li>
            @*            <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#product-edit-option">Thông tin tùy chọn</a>
            </li>*@
            @* <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#product-edit-description">Mô tả</a>
            </li>*@
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Mã loại sản phẩm</label>
                        <input type="text" class="form-control" asp-for="MaLoai" id="maSanPhamInput" />
                    </div>


                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tên loại sản phẩm</label>
                        <input type="text" class="form-control" asp-for="TenLoai" />
                    </div>
                    <td class="row">
                        <button class="btn btn-primary">
                            <i class="anticon anticon-save"></i>
                            <span>Thêm sản phẩm</span>
                        </button>
                        <button class="btn btn-secondary">
                            <a asp-area="Admin" asp-controller="Loais" asp-action="Index" asp-route-page="@ViewBag.CurrentPage" asp-route-MaID="@ViewBag.CurrentMaID" asp-route-MaDM="@ViewBag.CurrentMaDM" asp-route-Search="@ViewBag.CurrentSearch" asp-route-MinPrice="@ViewBag.CurrentMinPrice" style="color: white" asp-route-MaxPrice="@ViewBag.CurrentMaxPrice">Trở lại</a>
                        </button>
                    </td>
                    
                </div>
            </div>
        </div>
      
    </div>
</form>


@section Scripts {
    <script>
        // Đảm bảo rằng trang đã tải hoàn toàn trước khi thực thi mã JavaScript
        $(document).ready(function () {
            // Gán giá trị mặc định cho cột Mã sản phẩm
            $("#maSanPhamInput").val("L");

            // Sử dụng sự kiện 'input' để theo dõi thay đổi trong cột Mã sản phẩm
            $("#maSanPhamInput").on('input', function () {
                var inputValue = $(this).val();
                // Kiểm tra nếu độ dài của giá trị nhập vào là 0 (trống) hoặc lớn hơn 6 ký tự, thì không thay đổi giá trị
                if (inputValue.length === 0) {
                    $(this).val("L");
                } else if (inputValue.length > 6) {
                    // Giới hạn độ dài tối đa là 6 ký tự
                    $(this).val(inputValue.slice(0, 6));
                }
            });
            CKEDITOR.replace('txtDetail', {
                customConfig: '/Content/ckeditor/config.js',
                extraAllowedContent: 'span',
            });
        });

    </script>
}

Areas/Admin/Views/Loais/Delete.cshtml
@model MyPhamCheilinus.Models.Loai

@{
    string CurrentMaDM = ViewBag.CurrentMaDM;
    string CurrentSearch = ViewBag.CurrentSearch;
    int CurrentPage = ViewBag.CurrentPage;
    double? CurrentMinPrice = ViewBag.CurrentMinPrice;
    double? CurrentMaxPrice = ViewBag.CurrentMaxPrice;
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="~/Home">Trang chủ</a></li>
                <a class="breadcrumb-item" asp-area="Admin" asp-controller="Loais" asp-action="Index">Danh sách loại sản phẩm</a>
                <li class="breadcrumb-item active">Xóa loại sản phẩm</li>
            </ol>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="card-body">
    <h3>Bạn có chắc muốn xóa loại sản phẩm này?</h3>
    <div class="card">
        <div class="table">
            <table class="">
                <tbody>
                    <tr>
                        <td>Mã sản phẩm:</td>
                        <td class="text-dark font-weight-semibold">@Model.MaLoai</td>
                    </tr>
                    <tr>
                        <td>Tên sản phẩm:</td>
                        <td class="text-dark font-weight-semibold">@Model.TenLoai</td>
                    </tr>
                   
                <td class="row">
                    <form asp-action="Delete" asp-for="MaLoai" asp-route-page="@ViewBag.CurrentPage" asp-route-MaID="@ViewBag.CurrentMaID" asp-route-MaDM="@ViewBag.CurrentMaDM" asp-route-Search="@ViewBag.CurrentSearch" asp-route-MinPrice="@ViewBag.CurrentMinPrice" asp-route-MaxPrice="@ViewBag.CurrentMaxPrice">

                        <input type="submit" value="Xóa" class="btn btn-danger" /> |
                    </form>
                    <div>
                        <form asp-action="Details" asp-for="MaLoai" asp-route-page="@ViewBag.CurrentPage" asp-route-MaID="@ViewBag.CurrentMaID" asp-route-MaDM="@ViewBag.CurrentMaDM" asp-route-Search="@ViewBag.CurrentSearch" asp-route-MinPrice="@ViewBag.CurrentMinPrice" asp-route-MaxPrice="@ViewBag.CurrentMaxPrice">
                            <input type="submit" class="btn btn-secondary" value="Trở lại" />
                        </form>
                    </div>

                </td>
                </tbody>
            </table>

        </div>
    </div>
</div>
@section Scripts {
    <script>
        // Đảm bảo rằng trang đã tải hoàn toàn trước khi thực thi mã JavaScript
        $(document).ready(function () {
            CKEDITOR.replace('txtDetail', {
                customConfig: '/Content/ckeditor/config.js',
                extraAllowedContent: 'span',
            });
        });

    </script>
}

Areas/Admin/Views/Loais/Details.cshtml
@model MyPhamCheilinus.Models.Loai

@{
    ViewData["Title"] = "Chi tiết loại sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="~/Home">Trang chủ</a></li>
                <a class="breadcrumb-item" asp-area="Admin" asp-controller="Loais" asp-action="Index">Danh sách loại sản phẩm</a>
                <li class="breadcrumb-item active">Chi tiết loại sản phẩm</li>
            </ol>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="card-body">
    <h3>Thông tin chi tiết của loại sản phẩm:</h3>
    <div class="card">
        <div class="table">
            <table class="">
                <tbody>
                    <tr>
                        <td>Mã loại sản phẩm:</td>
                        <td class="text-dark font-weight-semibold">@Model.MaLoai</td>
                    </tr>
                    <tr>
                        <td>Tên loại sản phẩm:</td>
                        <td class="text-dark font-weight-semibold">@Model.TenLoai</td>
                    </tr>  
                    <tr>
                        <td>
                            <form asp-action="Details" asp-for="MaDanhMuc" asp-route-TenLoai="@ViewBag.CurrentLoai" asp-route-page="@ViewBag.CurrentPage">
                                <a asp-action="Edit" class="btn btn-success" asp-route-TenLoai="@ViewBag.CurrentLoai" asp-route-id="@Model.MaLoai" asp-route-page="@ViewBag.CurrentPage" >Sửa thông tin</a> |
                                <input type="submit" class="btn btn-secondary" id="backToList" value="Trở lại" />
                            </form>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

Areas/Admin/Views/Loais/Edit.cshtml
@model MyPhamCheilinus.Models.Loai

@{
    ViewData["Title"] = "Sửa thông tin loại sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section Styles{
    <link href="~/Adminassets/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/Adminassets/summernote/summernote.css" rel="stylesheet" />
}
<form asp-controller="Loais" asp-action="Edit" asp-route-page="@ViewBag.CurrentPage" asp-route-Loai="@ViewBag.CurrentLoai" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="All" class="text-danger"></div>
    <input type="hidden" asp-for="MaLoai" />
    <section>
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-md-6">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="~/Home">Trang chủ</a></li>
                        <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Loais" asp-action="Index" asp-route-page="@ViewBag.CurrentPage">Danh sách loại sản phẩm</a></li>
                        <li class="breadcrumb-item active">Sửa thông tin loại sản phẩm</li>
                    </ol>
                </div>
                <div class="col-md-6 text-right">
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <div class="page-header no-gutters has-tab">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Thông tin</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Mã loại sản phẩm</label>
                        <input type="text" class="form-control" asp-for="MaLoai" id="maSanPhamInput" readonly />
                    </div>


                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tên loại sản phẩm</label>
                        <input type="text" class="form-control" asp-for="TenLoai" />
                    </div>

                    <td class="row">
                        <button class="btn btn-primary">
                            <i class="anticon anticon-save"></i>
                            <span>Sửa</span>
                        </button>
                        <button class="btn btn-secondary">
                            <a asp-area="Admin" asp-controller="Loais" asp-action="Index" asp-route-page="@ViewBag.CurrentPage" asp-route-TenLoai="@ViewBag.CurrentLoai" style="color: white" >Trở lại</a>
                        </button>
                    </td>

                </div>
            </div>
        </div>

    </div>
</form>
@section Scripts {
    <script>
        // Đảm bảo rằng trang đã tải hoàn toàn trước khi thực thi mã JavaScript
        $(document).ready(function () {
            CKEDITOR.replace('txtDetail', {
                customConfig: '/Content/ckeditor/config.js',
                extraAllowedContent: 'span',
            });
        });

    </script>
}