Models/Role.cs
using System;
using System.Collections.Generic;

namespace MyPhamCheilinus.Models;

public partial class Role
{
    public int RoleId { get; set; }

    public string? RoleName { get; set; }

    public string? Description { get; set; }

    public virtual ICollection<Account> Accounts { get; set; } = new List<Account>();
}

Areas/Admin/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using MyPhamCheilinus.Helpper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyPhamCheilinus.Models;
using PagedList.Core;
using System.Data;
using Microsoft.AspNetCore.Authorization;

namespace MyPhamCheilinus.Areas.Admin.Controllers
{
    [Area("Admin")]
   
    public class RolesController : Controller
    {
        private readonly _2023MyPhamContext _context;
        public INotyfService _notifyService { get; }

        public RolesController(_2023MyPhamContext context, INotyfService notifyService)
        {
            _context = context;
            _notifyService = notifyService;
        }

        // GET: Admin/Roles
        public IActionResult Index(int? page, string? search = "", string? moTa="")
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 10;

            IQueryable<Role> query = _context.Roles
                .AsNoTracking();
            if (!string.IsNullOrEmpty(search))
            {
                query = query.Where(x => x.RoleName.Contains(search));
            }
            if (!string.IsNullOrEmpty(moTa))
            {
                query = query.Where(x => x.Description.Contains(moTa));
            }

   

            var lsProducts = query.OrderByDescending(x => x.RoleId).ToList();

            PagedList<Role> models = new PagedList<Role>(lsProducts.AsQueryable(), pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            ViewBag.CurrentSearch = search;
            ViewBag.CurrentMoTa = moTa;
        

            return View(models);
        }
        public IActionResult Filtter(string? search, string? moTa)
        {
            var url = "/Admin/Roles?";

           

            if (!string.IsNullOrEmpty(search))
            {
                url += $"search={search}&";
            }

            if (!string.IsNullOrEmpty(moTa))
            {
                url += $"moTa={moTa}&";
            }

            // Loại bỏ dấu '&' cuối cùng nếu có
            if (url.EndsWith("&"))
            {
                url = url.Substring(0, url.Length - 1);
            }

            return Json(new { status = "success", redirectUrl = url });
        }

       

        // GET: Admin/Roles/Details/5
        public async Task<IActionResult> Details(int? id, int? MaID, string? search, int? page, string? moTa)
        {
            if (id == null || _context.Roles == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.RoleId == id);
            if (role == null)
            {
                return NotFound();
            }
            ViewBag.CurrentPage = page;
            ViewBag.CurrentSearch = search;
            ViewBag.CurrentMaID = MaID;
            ViewBag.CurrentMoTa = moTa;
            ViewBag.Currentid = id;
            return View(role);
        }
        [HttpPost, ActionName("Details")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DetailsConfirmed(string? search, int? page, int? id, int? MaID, string? moTa)
        {
            if (_context.SanPhams == null)
            {
                return Problem("Entity set '_2023MyPhamContext.SanPhams' is null.");
            }
            // Sau khi xóa thành công, bạn có thể chuyển hướng trở lại trang chứa sản phẩm vừa xóa bằng cách truyền tham số `page`.
            // Nếu `page` không có giá trị, bạn có thể mặc định nó về một trang cụ thể (ví dụ: 1).
            return RedirectToAction("Index", new
            {
                page = page,
                MaID = MaID,
                search = search,
                moTa = moTa
            });
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Create(int? id, int? MaID, string? search, int? page, string? moTa)
        {
            ViewBag.CurrentPage = page;
            ViewBag.CurrentSearch = search;
            ViewBag.CurrentMaID = MaID;
            ViewBag.CurrentMoTa = moTa;
            ViewBag.Currentid = id;
            return View();
        }

        // POST: Admin/Roles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( int? page, [Bind("RoleId,RoleName,Description")] Role role)
        {
            if (string.IsNullOrEmpty(role.RoleName))
            {
                ModelState.AddModelError("RoleName", "Xin hãy nhập tên của người dùng.");
            }

            if (string.IsNullOrEmpty(role.Description))
            {
                ModelState.AddModelError("Description", "Xin hãy điền phần mô tả");
            }

            if (ModelState.IsValid)
            {
                _context.Add(role);
                await _context.SaveChangesAsync();
                _notifyService.Success("Tạo mới thành công");
                return RedirectToAction("Index", new
                {
                    page = page,

                });
            }
            return View(role);
        }

        // GET: Admin/Roles/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, int? MaID, string? search, int? page, string? moTa)
        {
            if (id == null || _context.Roles == null)
            {
                return NotFound();
            }

            var role = await _context.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            ViewBag.CurrentPage = page;
            ViewBag.CurrentSearch = search;
            ViewBag.CurrentMaID = MaID;
            ViewBag.CurrentMoTa = moTa;
            ViewBag.Currentid = id;

            return View(role);
        }

        // POST: Admin/Roles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, int? MaID, string? search, int? page, string? moTa, [Bind("RoleId,RoleName,Description")] Role role)
        {
            if (id != role.RoleId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(role);
                    await _context.SaveChangesAsync();
                    _notifyService.Success("Cập nhật thành công");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoleExists(role.RoleId))
                    {
                        _notifyService.Success("Có lỗi xảy ra");
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", new
                {
                    search = search,
                    page = page,
                    moTa = moTa,
                    MaID = MaID
                });
            }
            return View(role);
        }
        [Authorize(Roles = "Admin")]
        // GET: Admin/Roles/Delete/5
        public async Task<IActionResult> Delete(int? id, int? MaID, string? search, int? page, string? moTa)
        {
            if (id == null || _context.Roles == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.RoleId == id);
            if (role == null)
            {
                return NotFound();
            }
            ViewBag.CurrentPage = page;
            ViewBag.CurrentSearch = search;
            ViewBag.CurrentMaID = MaID;
            ViewBag.CurrentMoTa = moTa;
            ViewBag.Currentid = id;
            return View(role);
        }

        // POST: Admin/Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id, int? MaID, string? search, int? page, string? moTa)
        {
            if (_context.Roles == null)
            {
                return Problem("Entity set '_2023MyPhamContext.Roles'  is null.");
            }
            var role = await _context.Roles.FindAsync(id);
            var account = await _context.Accounts.Where(p => p.AccountId == id).ToListAsync();
            _context.RemoveRange(account);
            _context.Roles.Remove(role);
            await _context.SaveChangesAsync();
            _notifyService.Success("Xóa quyền truy cập thành công");
            return RedirectToAction("Index", new
            {
                page = page,
                MaID = MaID,
                search = search,
                moTa = moTa
            });
        }
        private bool RoleExists(int id)
        {
          return (_context.Roles?.Any(e => e.RoleId == id)).GetValueOrDefault();
        }
    }
}

Areas/Admin/Views/Roles/Create.cshtml
@model MyPhamCheilinus.Models.Role

@{
    ViewData["Title"] = "Thêm mới quyền truy cập";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<section>
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-md-6">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="~/Home">Trang chủ</a></li>
                    <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Roles" asp-action="Index" asp-route-page="@ViewBag.CurrentPage">Danh sách quyền truy cập</a></li>
                    <li class="breadcrumb-item active">Thêm mới quyền truy cập</li>
                </ol>
            </div>
            <div class="col-md-6 text-right">
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<div class="card-body">
    <h3>Nhập thông tin quyền truy cập:</h3>
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    <form asp-action="Create" asp-route-MaID="@ViewBag.CurrentMaID" asp-route-page="@ViewBag.CurrentPage" asp-route-Search="@ViewBag.CurrentSearch" asp-route-MoTa="@ViewBag.CurrentMoTa">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label>Quyền truy cập:</label>
                            <input asp-for="RoleName" class="form-control" />
                            <span asp-validation-for="RoleName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label>Mô tả:</label>
                            <input asp-for="Description" class="form-control" />
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Tạo mới" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>

            <div>
                <a asp-action="Index" asp-route-MaID="@ViewBag.CurrentMaID" asp-route-page="@ViewBag.CurrentPage" asp-route-Search="@ViewBag.CurrentSearch" asp-route-MoTa="@ViewBag.CurrentMoTa">Trở lại danh sách</a>
            </div>

        </div>
    </div>
</div>

   

Areas/Admin/Views/Roles/Delete.cshtml
@model MyPhamCheilinus.Models.Role
@{
    ViewData["Title"] = "Xóa quyền truy cập";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<section>
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-md-6">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="~/Home">Trang chủ</a></li>
                    <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Roles" asp-action="Index" asp-route-page="@ViewBag.CurrentPage">Danh sách quyền truy cập</a></li>
                    <li class="breadcrumb-item active">Xóa quyền truy cập</li>
                </ol>
            </div>
            <div class="col-md-6 text-right">
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="card-body">
    <h3>Bạn có chắc chắn là muốn xóa quyền truy cập này?</h3>
    <div class="card">
        <div class="table">
            <table class="">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.RoleId</td>
                    </tr>
                    <tr>
                        <td>Tên người dùng:</td>
                        <td class="text-dark font-weight-semibold">@Model.RoleName</td>
                    </tr>
                    <tr>
                        <td>Mô tả:</td>
                        <td>@Model.Description</td>

                    </tr>
                    <tr>
                        <td>
                            <form asp-action="Delete" asp-route-MaID="@ViewBag.CurrentMaID" asp-route-page="@ViewBag.CurrentPage" asp-route-Search="@ViewBag.CurrentSearch" asp-route-MoTa="@ViewBag.CurrentMoTa">
                                <input type="hidden" asp-for="RoleId" />
                                <input type="submit" value="Xóa" class="btn btn-danger" /> |
                                <a asp-action="Index" asp-route-MaID="@ViewBag.CurrentMaID" asp-route-page="@ViewBag.CurrentPage" asp-route-Search="@ViewBag.CurrentSearch" asp-route-MoTa="@ViewBag.CurrentMoTa">Trở lại</a>
                            </form>
                        </td>
                        <td></td>

                    </tr>

                </tbody>
            </table>
        </div>
    </div>
</div>

Areas/Admin/Views/Roles/Details.cshtml
@model MyPhamCheilinus.Models.Role
@{
    ViewData["Title"] = "Thông tin quyền truy cập";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}<section>
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-md-6">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="~/Home">Trang chủ</a></li>
                    <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Roles" asp-action="Index" asp-route-page="@ViewBag.CurrentPage">Danh sách sản phẩm</a></li>
                    <li class="breadcrumb-item active">Thêm mới người dùng</li>
                </ol>
            </div>
            <div class="col-md-6 text-right">
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="card-body">
    <h3>Thông tin quyền truy cập:</h3>
    <div class="card">
        <div class="table">
            <table class="">
                <tbody>
                    <tr>
                        <td>Quyền truy cập:</td>
                        <td class="text-dark font-weight-semibold">@Model.RoleName</td>
                    </tr>
                    <tr>
                        <td>Mô tả:</td>
                        <td>@Model.Description</td>

                    </tr>
                    <tr>
                        <td>           
                            <a asp-action="Edit" class="btn btn-success" asp-route-id="@Model.RoleId" asp-route-MaID="@ViewBag.CurrentMaID" asp-route-page="@ViewBag.CurrentPage" asp-route-Search="@ViewBag.CurrentSearch" asp-route-MoTa="@ViewBag.CurrentMoTa">Sửa thông tin</a> |
                            <a asp-action="Index" asp-route-MaID="@ViewBag.CurrentMaID" asp-route-page="@ViewBag.CurrentPage" asp-route-Search="@ViewBag.CurrentSearch" asp-route-MoTa="@ViewBag.CurrentMoTa">Trở lại</a>
                        </td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

Areas/Admin/Views/Roles/Edit.cshtml
@model MyPhamCheilinus.Models.Role
@{
    ViewData["Title"] = "Cập nhật quyền truy cập";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<h1>@ViewBag.Currentid</h1>
<h1>@ViewBag.CurrentMaID</h1>
<section>
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-md-6">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="~/Home">Trang chủ</a></li>
                    <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Roles" asp-action="Index" asp-route-page="@ViewBag.CurrentPage">Danh sách quyền truy cập</a></li>
                    <li class="breadcrumb-item active">Cập nhật quyền truy cập</li>
                </ol>
            </div>
            <div class="col-md-6 text-right">
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="card-body">
    <h3>Cập nhật thông tin quyền truy cập:</h3>
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    <form asp-action="Edit" asp-route-MaID="@ViewBag.CurrentMaID" asp-route-page="@ViewBag.CurrentPage" asp-route-Search="@ViewBag.CurrentSearch" asp-route-MoTa="@ViewBag.CurrentMoTa">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <input type="hidden" asp-for="RoleId" />
                        <div class="form-group">
                            <label>Quyền truy cập</label>
                            <input asp-for="RoleName" class="form-control" />
                            <span asp-validation-for="RoleName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label>Mô tả</label>
                            <input asp-for="Description" class="form-control" />
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        <div class="form-group" asp-route-Id="@ViewBag.CurrentId1" asp-route-page="@ViewBag.CurrentPage" asp-route-Search="@ViewBag.CurrentSearch" asp-route-MoTa="@ViewBag.CurrentMoTa">
                            <input type="submit"  value="Lưu" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>

            <div>
                <a asp-action="Index" asp-route-MaID="@ViewBag.CurrentMaID" asp-route-page="@ViewBag.CurrentPage" asp-route-Search="@ViewBag.CurrentSearch" asp-route-MoTa="@ViewBag.CurrentMoTa">Trở lại danh sách</a>
            </div>

        </div>
    </div>
</div>